Repository AlgorithmWarriors/3M500, pull requests merged in 2021-01, with the labels that each got.

#1 Readme 작성/ 초기 설정
  .github/.gitmessage.txt
  README.md
Labels: init

#3 배달,게임 아이템,방문길이,Max값이 정해진 큐
  CH_Python/Delivary.py
  CH_Python/GameItem.py
  CH_Python/MAX_FIFO_Queue.py
  CH_Python/VisitLength.py
Labels: feature

#2 가장 긴 팰린드롬
  JBJ_Javascript/longestPalindrome.js
Labels: feature

#4 N-Queen,FloodFill
  CH_Python/FloodFill.py
  CH_Python/N-queen.py
Labels: feature

#7 01/06 문제풀이
  JBJ_Javascript/124Number.js
  JBJ_Javascript/craneDollDraw.js
  JBJ_Javascript/sumOfTwo.js
Labels: feature

#6 버스 경로
  CH_Python/BusTravel.py
Labels: feature

#8 01/07-8,10 문제
  JBJ_Javascript/fourRulesCalculation.js
  JBJ_Javascript/loser.js
  JBJ_Javascript/skillTree.js
  JBJ_Javascript/terrainMove.js
  JBJ_Javascript/triangleSnail.js
Labels: feature, help wanted, recommend

#9 solve : 사칙연산
  CH_Python/CountEven.py
  CH_Python/Immigration.py
  CH_Python/Operations.py
  CH_Python/Stealing.py
  CH_Python/TerrainMovement.py
Labels: feature

#13 1/14-15,18-22 문제풀이
  .gitignore
  JBJ_Javascript/bestAlbum.js
  JBJ_Javascript/keypad.js
  JBJ_Javascript/largestSquare.js
  JBJ_Javascript/newsClustering.js
  JBJ_Javascript/nightShiftIndices.js
  JBJ_Javascript/openChat.js
  JBJ_Javascript/removeDuplication.js
  JBJ_Javascript/reverseTernary.js
  JBJ_Javascript/thanksgivingTraffic.js
Labels: feature
